version: '2'
services:
  smajoie_db:
    container_name: smajoie_db
    image: mariadb:10.10
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - smajoie_backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    
  smajoie_wordpress:
    container_name: smajoie_wordpress
    depends_on:
      - smajoie_db
    image: wordpress:php8.1
    volumes:
      - ./data:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: unless-stopped
    networks:
      - smajoie_backend
      - proxy
    environment:
      WORDPRESS_DB_HOST: smajoie_db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX}
    labels:
      - traefik.enable=true
      - traefik.http.routers.smajoie.entrypoints=http
      - traefik.http.routers.smajoie.rule=Host("smajoie.ch", "www.smajoie.ch")
      - traefik.http.middlewares.smajoie-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.smajoie.middlewares=smajoie-https-redirect
      - traefik.http.routers.smajoie-secure.entrypoints=https
      - traefik.http.routers.smajoie-secure.rule=Host("smajoie.ch", "www.smajoie.ch")
      - traefik.http.routers.smajoie-secure.tls=true
      - traefik.http.routers.smajoie-secure.tls.certresolver=http
      - traefik.docker.network=proxy
      
  smajoie_redis:
      image: redis:7

networks:
  smajoie_backend:
  proxy:
    external: true
